name: SvelteKit Deploy (Staging)

on:
  schedule:
    - cron: '0 * * * 0' # Every Sunday of the month
  push:
    branches: ['main']
  pull_request_target:
    branches: ['main']    
  workflow_dispatch:
     inputs:
      dry_run:
        description: 'Dry run'
        default: true
        required: true
        type: boolean
concurrency: # Multiple jobs should NOT run at the same time
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  build:
    env:
      CPANEL_TOKEN: ${{ secrets.CPANEL_TOKEN }}
      REPO_URL: ${{ secrets.REPO_URL }}
      RSA_ID: ${{ secrets.SSH_RSA_ID }} # SSH private key stored as a secret
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Set up the SSH key for git access
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_RSA_ID }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7822 ubsc.hosting2.acm.org >> ~/.ssh/known_hosts
        shell: bash

      # Deploy to fly.io
      - name: Deploy to A2Hosting
        if: ${{ inputs.dry_run == false && github.event_name != 'pull_request_target' }}
        run: | 
         npm install
         npm run build
         # Clone the remote repository using SSH (no password needed)
         git clone $REPO_URL app
         cd app
         mv .git ../build
         cd ..
         rm -rf app
         cd build
         git add .
         git commit -m "Autobuild: Generated by GitHub"
         git push
